version: '3.8'
services:
  north_south_pg_container:
    image: postgres:16.3
    container_name: north_south_pg_container
    restart: always
    environment:
      POSTGRES_DB: bd_north_south
      POSTGRES_USER: user_north_south
      POSTGRES_PASSWORD: 2ugYRUJHGfh3
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - 5432:5432
